name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # Run manually
  workflow_dispatch:
  # Run on pushes to main/master
  push: { branches: ["master", "main"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Output file name 
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          
          # User info
          user: owuorviny109
          template: classic
          config_timezone: Africa/Nairobi
          
          # The "Cross/Spider" Chart (Followup Plugin)
          base: ""
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_followup_indepth: yes
